spring:
  profiles:
    default: mysql
---
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usay_test
    username: usay
    password:

  sql:
    init:
      mode: always
      platform: h2
      data-locations: classpath:/db/data.sql

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

---
spring:
  config.activate.on-profile: test

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create

---
spring:
  config.activate.on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect