spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usay_test
    username: usay
    password:

  sql:
    init:
      platform: h2
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    initialization-mode: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace